snetsystems/cloudhub

.vscode/launch.json
Makefile
backend/server/mux.go
backend/server/redoc.go
backend/server/swagger.go
backend/server/swagger.json
backend/server/swagger_v2.yml

jack: Make API Spec. documentation using Swagger

---

frontend/src/agent_admin/components/AgentCodeEditor.tsx
frontend/src/agent_admin/containers/AgentConfiguration.tsx

Collector Config in Agent Configuration #123

Dev 0.9.1 dbchoe: Collector Config in Agent Configuration #123

---

frontend/src/agent_admin/components/AgentConfigurationTable.tsx
frontend/src/agent_admin/components/AgentControlTable.tsx
frontend/src/agent_admin/components/AgentMinionsTable.tsx
frontend/src/agent_admin/containers/AgentMinions.tsx

Only the rows in the Accept state have a click event

Dev 0.9.2 dbchoe

---

frontend/src/addon/128t/components/GeoLocationIndicator.tsx
frontend/src/addon/128t/components/RouterTable.tsx
frontend/src/addon/128t/containers/GridLayoutRenderer.tsx
frontend/src/addon/128t/types/index.ts
frontend/src/addon/128t/types/routers.ts
frontend/src/agent_admin/components/Agent.scss
frontend/src/agent_admin/components/AgentControlTable.tsx
frontend/src/agent_admin/constants/agentStatus.ts
frontend/src/agent_admin/constants/directory.ts
frontend/src/agent_admin/constants/index.ts
frontend/src/agent_admin/containers/AgentControl.tsx
frontend/src/agent_admin/type/agent.ts
frontend/src/agent_admin/type/index.ts
frontend/src/shared/apis/saltStack.ts

Telegraf package version choosable #142

Dev 1.0.1 dbchoe

---

frontend/src/addon/128t/components/RouterTable.tsx
frontend/src/style/components/react-tooltips.scss

The following issues have been included.
The Tooltip disappears #153
There is a risk that the router asset ID may be null, causing an error. #163

Dev 1.0.1 dbchoe office

---

frontend/src/CheckSources.tsx
frontend/src/agent_admin/containers/AgentConfiguration.tsx
frontend/src/shared/copy/notifications.ts
frontend/src/shared/middleware/errors.js
frontend/src/sources/containers/ManageSources.tsx

1. Changed the timing to get the organizations as what it'll be gotten after login
2. Removed the unnecessary routine.

Dev 1.0.1 jack

---

README.md
frontend/src/dashboards/components/CellEditorOverlay.tsx
frontend/src/logs/components/LogsHeader.tsx
frontend/src/logs/containers/LogsPage.tsx
frontend/src/shared/components/DatabaseList.tsx
frontend/src/shared/components/TimeMachine/FluxQueryMaker.tsx
frontend/src/shared/components/TimeMachine/FluxScriptWizard.tsx
frontend/src/shared/utils/fluxScriptWizard.ts

Multi-tenant Feature #144
Apply groups to Visualize and LogViewer

Dev 1.0.1 jmroh

---

frontend/src/kapacitor/components/AlertOutputs.tsx
frontend/src/kapacitor/components/AlertTabs.tsx
frontend/src/kapacitor/components/KapacitorForm.tsx
frontend/src/kapacitor/components/KapacitorRule.tsx
frontend/src/kapacitor/components/RuleHandlers.tsx
frontend/src/kapacitor/constants/index.ts
frontend/src/kapacitor/containers/KapacitorPage.tsx
frontend/src/kapacitor/containers/KapacitorRulePage.tsx
frontend/src/types/kapacitor.ts

hsmun: #144 Email(SMTP) & Telegraf Super Admin Only
hsmun: #144 Alert Event handler Assignment

Dev 1.0.1 hyeonseok

---

frontend/src/addon/128t/containers/GridLayoutRenderer.tsx

hsmun: #192 Call Salt api by separating roles

hsmun: #192 Call Salt api by separating roles

---

frontend/src/addon/128t/components/DataPopup.tsx

dbchoe : 'esc' keyup data popup close

---

backend/server/mux.go
backend/server/routes.go
backend/server/swagger.json

/cloudhub/v1/salt to /cloudhub/v1/proxy/salt

Jack: rename the end point url for salt

---

frontend/src/dashboards/components/SourceSelector.tsx
frontend/src/data_explorer/containers/DataExplorer.tsx
frontend/src/shared/components/TimeMachine/CSVExporter.tsx
frontend/src/shared/components/TimeMachine/TimeMachine.tsx
frontend/src/shared/components/TimeMachine/TimeMachineControls.tsx
frontend/src/shared/utils/downloadTimeseriesCSV.ts

- InfluxQL > Add Local Time Convert on CSV Download
- Rename Tab (Flux(Beta) -> Flux(Alpha))

hsmun: #249 Visualize > Queries Tab Enhancement

---

backend/server/terminal.go
frontend/src/shared/components/Shell.tsx

jmroh: #229 fix resizing the terminal

jmroh: #229 fix resizing the terminal

---

frontend/src/addon/128t/containers/GraphqlProvider.tsx
frontend/src/addon/128t/containers/SwanSdplexStatusPage.tsx

modifiy SWAN/Oncue SSL Certification issue

Dev 1.0.9 yongsik

---

frontend/src/CheckSources.tsx
frontend/src/hosts/actions/vspheres.ts
frontend/src/hosts/apis/index.ts
frontend/src/hosts/containers/VMHostsPage.tsx
frontend/src/index.tsx
frontend/src/sources/actions/index.ts
frontend/src/sources/components/InfluxTable.tsx
frontend/src/sources/components/InfluxTableRow.tsx
frontend/src/sources/containers/ManageSources.tsx
frontend/src/sources/reducers/index.ts
frontend/src/store/configureStore.js

When storing vSphere access information, the data source is also stored.
fixsed #258

Dev 1.0.10 dbchoe

---

etc/build.py

The target path was missing in the go build command

fix: go build target path

---

frontend/src/hosts/containers/HostsPage.tsx
frontend/src/hosts/containers/Infrastructure.tsx

1. bug fixed. manualReferesh && manualRefresh filterLayout by Private or AWS
2. bug fixed . Avoid redundant rendering due to incorrect routing && remove isUsing Vsphere check code

Dev 1.1.1 hotfix dbchoe

---

frontend/src/addon/128t/containers/GridLayoutRenderer.tsx
frontend/src/agent_admin/containers/AgentControl.tsx
frontend/src/agent_admin/containers/ServiceConfig.tsx
frontend/src/clouds/components/OpenStackPageInstanceDetail.tsx
frontend/src/clouds/components/OpenStackPageProjectTable.tsx

OpenStack Monitoring Feature #361 #362

---

backend/server/csp.go
frontend/src/admin/containers/cloudhub/ProviderConfPage.tsx

At #362 Add OSP telegraf InsecureSkipVerify option

---

backend/kv/internal/internal.proto

At #402 Fix Change order of DashboardCell proto

---

backend/canned/openstack.json
backend/server/csp.go
frontend/src/agent_admin/constants/CollectorConfigTable.ts
frontend/src/agent_admin/containers/ServiceConfig.tsx

Added the default option for collecting into the telegraf config for OSP

---

frontend/src/hosts/apis/index.ts
frontend/src/hosts/components/TopologyPreferences.tsx
frontend/src/hosts/components/TopologyTooltip.tsx
frontend/src/hosts/configurations/topology.ts
frontend/src/hosts/constants/topology.ts
frontend/src/hosts/containers/InventoryTopology.tsx

Fix Empty Hostname Output when 'hostname' Tag is Missing

---

backend/canned/procstat.json
frontend/src/hosts/apis/index.ts
frontend/src/hosts/components/TopologyHostDetailTable.tsx
frontend/src/hosts/types/agent.ts
frontend/src/hosts/utils/index.ts

Fix Issue with Nested Objects in grains.items Response Handling

---

frontend/src/addon/128t/components/128t.scss
frontend/src/agent_admin/apis/index.ts
frontend/src/alerts/components/AlertsTable.tsx
frontend/src/hosts/components/HostRow.tsx
frontend/src/hosts/components/HostsPageAwsTabTableRow.tsx
frontend/src/hosts/components/HostsPageGcpTabTableRow.tsx
frontend/src/hosts/configurations/topology.ts
frontend/src/hosts/constants/topology.ts
frontend/src/hosts/utils/topology.ts
frontend/src/shared/apis/saltStack.ts

Topology node별 Agent border에 상태 색상 표시 & Alert Table Scroll 버그

---

Makefile
backend/server/swagger.json
frontend/package.json
frontend/src/clouds/components/KubernetesHexagon.tsx
frontend/src/clouds/containers/KubernetesPage.tsx
frontend/src/hosts/containers/InventoryTopology.tsx

IPMI 모니터링 그래프 미출력 문제 & An error occurred while loading the Kubernetes dashboard

---

Makefile
backend/canned/ipmi_sensor.json
backend/server/swagger.json
frontend/package.json
frontend/src/alerts/components/AlertsTable.tsx
frontend/src/alerts/components/AlertsTableRow.tsx
frontend/src/hosts/apis/index.ts

Alert table staus warning 색상 오류 & Inventory Topology에 Supermicro 장비의 전력 사용량 및 온도 태그 추가

---

Makefile
backend/server/swagger.json
frontend/package.json
frontend/src/hosts/apis/index.ts

Inventory Topology 노드의 디스크 상태 Window Disk Query 수정

---

backend/server/network_devices.go
frontend/src/device_management/components/LearningSettingModal.tsx

[CloudHub AI] Refactor Device Deletion Logic &  Fix bug in ML/DL Setting modal to reset isUpdateAfterCreate state

---

Makefile
etc/build.py

Add 'CGO_ENABLED=0' to go build options in Makefile & Fix cloudhub build command to correctly pass 'CGO_ENABLED=0'
